apiVersion: v2
type: application
# renovate: datasource=docker depName=dock.mau.dev/mautrix/whatsapp
appVersion: v25.10
description: A Matrix-WhatsApp puppeting bridge https://maunium.net/go/mautrix-whatsapp
name: mautrix-whatsapp
version: 1.7.0
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - whatsapp
home: https://maunium.net/go/mautrix-whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: Yves Siegrist
    email: yves@siegrist.io
